-- =============================================================================
-- 04_STORED_PROCEDURES: All 6 procedures with full source
-- =============================================================================
-- Run AFTER tables and seed data. These are the engine of the application.
--
-- FLOW:
--   SP_GENERATE_SENSOR_HISTORY → one-time, populates 90-day history
--   SP_GENERATE_SENSOR_BATCH   → called every 1 min by TASK_STREAM_SENSORS
--   SP_INJECT_DEGRADATION      → ad-hoc: demo/test degradation patterns
--   SP_SCORE_ALL               → called every 15 min by TASK_SCORE_ALL
--   SP_TRIAGE_ALERTS           → called every 15 min by TASK_TRIAGE_PIPELINE
--   SP_GENERATE_WO_DRAFTS      → called every 15 min by TASK_TRIAGE_PIPELINE
-- =============================================================================


-- ─── 1. SP_GENERATE_SENSOR_BATCH ─────────────────────────────────────────────
-- One reading per asset per call. Respects active degradation injections.
-- Uses CTE JOINs instead of correlated subqueries (Snowflake INSERT limitation).
-- Called by: TASK_STREAM_SENSORS (every 1 minute)
CREATE OR REPLACE PROCEDURE MFG_PDM_DB.RAW.SP_GENERATE_SENSOR_BATCH()
RETURNS VARCHAR
LANGUAGE SQL
COMMENT = 'Generates one sensor reading per asset for live streaming.'
EXECUTE AS CALLER
AS
$$
BEGIN
    INSERT INTO MFG_PDM_DB.RAW.SENSOR_READINGS (ASSET_ID, READING_TS, VIBRATION_MM_S, TEMPERATURE_C, RPM, PRESSURE_BAR, POWER_KW, SOURCE)
    WITH DEG_VIB AS (
        SELECT DI.ASSET_ID,
            LEAST(1.0, DATEDIFF('hour', DI.START_TS, CURRENT_TIMESTAMP()) / NULLIF(DI.RAMP_HOURS, 0)) AS RAMP_PCT
        FROM MFG_PDM_DB.RAW.DEGRADATION_INJECTIONS DI
        WHERE DI.ACTIVE = TRUE AND DI.FAILURE_MODE IN ('BEARING_WEAR', 'IMBALANCE')
        QUALIFY ROW_NUMBER() OVER (PARTITION BY DI.ASSET_ID ORDER BY DI.START_TS DESC) = 1
    ),
    DEG_TEMP AS (
        SELECT DI.ASSET_ID,
            LEAST(1.0, DATEDIFF('hour', DI.START_TS, CURRENT_TIMESTAMP()) / NULLIF(DI.RAMP_HOURS, 0)) AS RAMP_PCT
        FROM MFG_PDM_DB.RAW.DEGRADATION_INJECTIONS DI
        WHERE DI.ACTIVE = TRUE AND DI.FAILURE_MODE IN ('OVERHEATING', 'LUBRICATION_FAILURE')
        QUALIFY ROW_NUMBER() OVER (PARTITION BY DI.ASSET_ID ORDER BY DI.START_TS DESC) = 1
    )
    SELECT
        A.ASSET_ID,
        DATE_TRUNC('minute', CURRENT_TIMESTAMP()),
        ROUND(GREATEST(0.5,
            (A.MAX_VIBRATION_MM_S * UNIFORM(40, 70, RANDOM()) / 100.0)
            + (UNIFORM(-100, 100, RANDOM()) / 100.0)
            + COALESCE(A.MAX_VIBRATION_MM_S * 0.4 * DV.RAMP_PCT, 0)
        ), 3),
        ROUND(GREATEST(15.0,
            (A.MAX_TEMP_C * UNIFORM(50, 75, RANDOM()) / 100.0)
            + (UNIFORM(-200, 200, RANDOM()) / 100.0)
            + COALESCE(A.MAX_TEMP_C * 0.3 * DT.RAMP_PCT, 0)
        ), 2),
        GREATEST(0, A.RATED_RPM + UNIFORM(-50, 50, RANDOM())),
        ROUND(UNIFORM(30, 80, RANDOM()) + UNIFORM(0, 99, RANDOM()) / 100.0, 2),
        ROUND(GREATEST(0, (A.RATED_RPM / 100.0) * UNIFORM(70, 130, RANDOM()) / 100.0 + UNIFORM(-5, 5, RANDOM())), 2),
        'STREAM'
    FROM MFG_PDM_DB.RAW.ASSETS A
    LEFT JOIN DEG_VIB DV ON A.ASSET_ID = DV.ASSET_ID
    LEFT JOIN DEG_TEMP DT ON A.ASSET_ID = DT.ASSET_ID;
    RETURN 'Generated ' || (SELECT COUNT(*) FROM MFG_PDM_DB.RAW.ASSETS) || ' sensor readings';
END;
$$;


-- ─── 2. SP_GENERATE_SENSOR_HISTORY ───────────────────────────────────────────
-- ONE-TIME: 90 days of 5-min interval data. ~1.5M rows. Takes 5-15 min on MEDIUM.
CREATE OR REPLACE PROCEDURE MFG_PDM_DB.RAW.SP_GENERATE_SENSOR_HISTORY()
RETURNS VARCHAR
LANGUAGE SQL
COMMENT = 'One-time: generates 90 days of historical sensor data at 5-min intervals (~1.5M rows).'
EXECUTE AS CALLER
AS
$$
BEGIN
    INSERT INTO MFG_PDM_DB.RAW.SENSOR_READINGS (ASSET_ID, READING_TS, VIBRATION_MM_S, TEMPERATURE_C, RPM, PRESSURE_BAR, POWER_KW, SOURCE)
    SELECT
        A.ASSET_ID,
        DATEADD('minute', -(T.N * 5), DATE_TRUNC('minute', CURRENT_TIMESTAMP())),
        ROUND(GREATEST(0.5,
            (A.MAX_VIBRATION_MM_S * 0.55)
            + (A.MAX_VIBRATION_MM_S * 0.08 * SIN(2 * 3.14159 * (MOD(T.N * 5, 1440)) / 1440.0))
            + (UNIFORM(-150, 150, RANDOM()) / 100.0)
        ), 3),
        ROUND(GREATEST(18.0,
            (A.MAX_TEMP_C * 0.60)
            + (A.MAX_TEMP_C * 0.06 * SIN(2 * 3.14159 * (MOD(T.N * 5, 1440)) / 1440.0 + 1.5))
            + (UNIFORM(-200, 200, RANDOM()) / 100.0)
        ), 2),
        CASE WHEN MOD(T.N, 96) = 95 AND UNIFORM(0,10,RANDOM()) < 2 THEN 0
             ELSE GREATEST(0, A.RATED_RPM + UNIFORM(-80, 80, RANDOM()))
        END,
        ROUND(UNIFORM(3000, 8000, RANDOM()) / 100.0, 2),
        ROUND(GREATEST(0.5, (A.RATED_RPM / 100.0) * UNIFORM(70, 130, RANDOM()) / 100.0 + UNIFORM(-300, 300, RANDOM()) / 100.0), 2),
        'HISTORY'
    FROM MFG_PDM_DB.RAW.ASSETS A
    CROSS JOIN (SELECT SEQ4() AS N FROM TABLE(GENERATOR(ROWCOUNT => 25920))) T
    WHERE T.N * 5 <= 90 * 24 * 60;
    RETURN 'Historical sensor data generation complete';
END;
$$;


-- ─── 3. SP_INJECT_DEGRADATION ────────────────────────────────────────────────
-- Ad-hoc: Simulate degradation on a specific asset for demos
-- Usage: CALL MFG_PDM_DB.RAW.SP_INJECT_DEGRADATION('CNC-001', 'BEARING_WEAR', 48.0);
CREATE OR REPLACE PROCEDURE MFG_PDM_DB.RAW.SP_INJECT_DEGRADATION(
    P_ASSET_ID VARCHAR, P_FAILURE_MODE VARCHAR, P_RAMP_HOURS FLOAT
)
RETURNS VARCHAR
LANGUAGE SQL
COMMENT = 'Injects a degradation pattern on a specific asset for demo/testing.'
EXECUTE AS CALLER
AS
$$
BEGIN
    UPDATE MFG_PDM_DB.RAW.DEGRADATION_INJECTIONS SET ACTIVE = FALSE WHERE ASSET_ID = :P_ASSET_ID;
    INSERT INTO MFG_PDM_DB.RAW.DEGRADATION_INJECTIONS (ASSET_ID, FAILURE_MODE, START_TS, RAMP_HOURS, ACTIVE)
    VALUES (:P_ASSET_ID, :P_FAILURE_MODE, CURRENT_TIMESTAMP(), :P_RAMP_HOURS, TRUE);
    RETURN 'Degradation injection started: ' || :P_ASSET_ID || ' / ' || :P_FAILURE_MODE || ' / ' || :P_RAMP_HOURS || 'h ramp';
END;
$$;


-- ─── 4. SP_SCORE_ALL ─────────────────────────────────────────────────────────
-- Runs anomaly detection + failure prediction + RUL estimation
-- Called by: TASK_SCORE_ALL (every 15 minutes)
CREATE OR REPLACE PROCEDURE MFG_PDM_DB.ML.SP_SCORE_ALL()
RETURNS VARCHAR
LANGUAGE SQL
COMMENT = 'Runs all ML scoring: anomaly detection, failure prediction, RUL estimation.'
EXECUTE AS CALLER
AS
$$
BEGIN
    -- 1. ANOMALY DETECTION: Z-score on vibration vs 7-day rolling stats
    MERGE INTO MFG_PDM_DB.ML.ANOMALY_SCORES T
    USING (
        WITH STATS AS (
            SELECT ASSET_ID, AVG(AVG_VIBRATION) AS MEAN_VIB, STDDEV(AVG_VIBRATION) AS STD_VIB
            FROM MFG_PDM_DB.CURATED.DT_SENSOR_FEATURES_15M
            WHERE WINDOW_START >= DATEADD('day', -7, CURRENT_TIMESTAMP())
            GROUP BY ASSET_ID
        ),
        LATEST AS (
            SELECT F.*, ROW_NUMBER() OVER (PARTITION BY F.ASSET_ID ORDER BY F.WINDOW_START DESC) AS RN
            FROM MFG_PDM_DB.CURATED.DT_SENSOR_FEATURES_15M F
        )
        SELECT L.ASSET_ID, L.WINDOW_START AS TS, L.AVG_VIBRATION AS VALUE, S.MEAN_VIB AS FORECAST,
            GREATEST(0, S.MEAN_VIB - 2.5 * COALESCE(S.STD_VIB, 0.5)) AS LOWER_BOUND,
            S.MEAN_VIB + 2.5 * COALESCE(S.STD_VIB, 0.5) AS UPPER_BOUND,
            CASE WHEN L.AVG_VIBRATION > S.MEAN_VIB + 2.5 * COALESCE(S.STD_VIB, 0.5) THEN TRUE ELSE FALSE END AS IS_ANOMALY,
            LEAST(1.0, GREATEST(0, ABS(L.AVG_VIBRATION - S.MEAN_VIB) / NULLIF(3 * S.STD_VIB, 0))) AS PERCENTILE,
            ROUND(ABS(L.AVG_VIBRATION - S.MEAN_VIB), 4) AS DISTANCE,
            CURRENT_TIMESTAMP() AS SCORED_AT
        FROM LATEST L JOIN STATS S ON L.ASSET_ID = S.ASSET_ID WHERE L.RN = 1
    ) S
    ON T.ASSET_ID = S.ASSET_ID AND T.TS = S.TS
    WHEN MATCHED THEN UPDATE SET T.VALUE=S.VALUE, T.FORECAST=S.FORECAST, T.LOWER_BOUND=S.LOWER_BOUND,
        T.UPPER_BOUND=S.UPPER_BOUND, T.IS_ANOMALY=S.IS_ANOMALY, T.PERCENTILE=S.PERCENTILE,
        T.DISTANCE=S.DISTANCE, T.SCORED_AT=S.SCORED_AT
    WHEN NOT MATCHED THEN INSERT VALUES (S.ASSET_ID, S.TS, S.VALUE, S.FORECAST, S.LOWER_BOUND,
        S.UPPER_BOUND, S.IS_ANOMALY, S.PERCENTILE, S.DISTANCE, S.SCORED_AT);

    -- 2. FAILURE PREDICTION: Composite score from threshold proximity + trend
    MERGE INTO MFG_PDM_DB.ML.FAILURE_PREDICTIONS T
    USING (
        SELECT H.ASSET_ID, CURRENT_TIMESTAMP() AS SCORED_AT,
            ROUND(LEAST(1.0, GREATEST(0,
                0.40 * COALESCE(H.VIB_PCT_OF_LIMIT, 0) + 0.30 * COALESCE(H.TEMP_PCT_OF_LIMIT, 0)
                + 0.15 * LEAST(1.0, GREATEST(0, COALESCE(H.VIB_DELTA, 0)) / NULLIF(A.MAX_VIBRATION_MM_S * 0.05, 0))
                + 0.15 * LEAST(1.0, GREATEST(0, COALESCE(H.STD_VIBRATION, 0)) / NULLIF(A.MAX_VIBRATION_MM_S * 0.15, 0))
            )), 4) AS FAILURE_PROB,
            CASE WHEN FAILURE_PROB >= 0.6 THEN 1 ELSE 0 END AS PREDICTED_CLASS,
            OBJECT_CONSTRUCT('vib_pct', H.VIB_PCT_OF_LIMIT, 'temp_pct', H.TEMP_PCT_OF_LIMIT,
                'vib_delta', H.VIB_DELTA, 'std_vib', H.STD_VIBRATION) AS TOP_FEATURES
        FROM MFG_PDM_DB.CURATED.DT_ASSET_HEALTH H
        JOIN MFG_PDM_DB.RAW.ASSETS A ON H.ASSET_ID = A.ASSET_ID
    ) S
    ON T.ASSET_ID = S.ASSET_ID
    WHEN MATCHED THEN UPDATE SET T.SCORED_AT=S.SCORED_AT, T.FAILURE_PROB=S.FAILURE_PROB,
        T.PREDICTED_CLASS=S.PREDICTED_CLASS, T.TOP_FEATURES=S.TOP_FEATURES
    WHEN NOT MATCHED THEN INSERT VALUES (S.ASSET_ID, S.SCORED_AT, S.FAILURE_PROB, S.PREDICTED_CLASS, S.TOP_FEATURES);

    -- 3. RUL ESTIMATION: Linear projection of vibration trend to threshold
    MERGE INTO MFG_PDM_DB.ML.RUL_ESTIMATES T
    USING (
        SELECT H.ASSET_ID, CURRENT_TIMESTAMP() AS ESTIMATED_AT, 168 AS FORECAST_HOURS,
            H.AVG_VIBRATION AS CURRENT_VIBRATION,
            ROUND(H.AVG_VIBRATION + COALESCE(H.VIB_DELTA, 0) * 168 / 0.25, 3) AS FORECASTED_VIBRATION,
            A.MAX_VIBRATION_MM_S AS MAX_VIBRATION_LIMIT,
            CASE WHEN COALESCE(H.VIB_DELTA, 0) <= 0 THEN 9999
                 ELSE ROUND(GREATEST(0, (A.MAX_VIBRATION_MM_S - H.AVG_VIBRATION) / (H.VIB_DELTA / 0.25)), 1)
            END AS ESTIMATED_RUL_HOURS
        FROM MFG_PDM_DB.CURATED.DT_ASSET_HEALTH H
        JOIN MFG_PDM_DB.RAW.ASSETS A ON H.ASSET_ID = A.ASSET_ID
    ) S
    ON T.ASSET_ID = S.ASSET_ID
    WHEN MATCHED THEN UPDATE SET T.ESTIMATED_AT=S.ESTIMATED_AT, T.FORECAST_HOURS=S.FORECAST_HOURS,
        T.CURRENT_VIBRATION=S.CURRENT_VIBRATION, T.FORECASTED_VIBRATION=S.FORECASTED_VIBRATION,
        T.MAX_VIBRATION_LIMIT=S.MAX_VIBRATION_LIMIT, T.ESTIMATED_RUL_HOURS=S.ESTIMATED_RUL_HOURS
    WHEN NOT MATCHED THEN INSERT VALUES (S.ASSET_ID, S.ESTIMATED_AT, S.FORECAST_HOURS, S.CURRENT_VIBRATION,
        S.FORECASTED_VIBRATION, S.MAX_VIBRATION_LIMIT, S.ESTIMATED_RUL_HOURS);

    RETURN 'ML scoring complete at ' || CURRENT_TIMESTAMP()::VARCHAR;
END;
$$;


-- ─── 5. SP_TRIAGE_ALERTS ────────────────────────────────────────────────────
-- Called by: TASK_TRIAGE_PIPELINE (every 15 minutes)
CREATE OR REPLACE PROCEDURE MFG_PDM_DB.OPS.SP_TRIAGE_ALERTS()
RETURNS VARCHAR
LANGUAGE SQL
COMMENT = 'Generates alerts from DT_ASSET_HEALTH + ML scores. Deduped hourly.'
EXECUTE AS CALLER
AS
$$
BEGIN
    -- Threshold breach alerts
    INSERT INTO MFG_PDM_DB.OPS.ALERT_HISTORY (ASSET_ID, ALERT_TYPE, SEVERITY, MESSAGE, DETAIL)
    SELECT H.ASSET_ID, 'THRESHOLD_BREACH', H.RULE_STATUS,
        H.ASSET_ID || ': ' || H.RULE_STATUS || ' - Vib=' || ROUND(H.AVG_VIBRATION,2) || 'mm/s (' || ROUND(H.VIB_PCT_OF_LIMIT*100,1) || '%), Temp=' || ROUND(H.AVG_TEMPERATURE,1) || 'C (' || ROUND(H.TEMP_PCT_OF_LIMIT*100,1) || '%)',
        OBJECT_CONSTRUCT('vibration', H.AVG_VIBRATION, 'temperature', H.AVG_TEMPERATURE, 'health_score', H.HEALTH_SCORE)
    FROM MFG_PDM_DB.CURATED.DT_ASSET_HEALTH H
    WHERE H.RULE_STATUS IN ('CRITICAL', 'WARNING')
    AND NOT EXISTS (SELECT 1 FROM MFG_PDM_DB.OPS.ALERT_HISTORY A WHERE A.ASSET_ID = H.ASSET_ID AND A.ALERT_TYPE = 'THRESHOLD_BREACH' AND A.ALERT_TS >= DATEADD('hour', -1, CURRENT_TIMESTAMP()));

    -- Failure prediction alerts (>60%)
    INSERT INTO MFG_PDM_DB.OPS.ALERT_HISTORY (ASSET_ID, ALERT_TYPE, SEVERITY, MESSAGE, DETAIL)
    SELECT FP.ASSET_ID, 'FAILURE_PREDICTION',
        CASE WHEN FP.FAILURE_PROB >= 0.80 THEN 'CRITICAL' WHEN FP.FAILURE_PROB >= 0.60 THEN 'WARNING' ELSE 'INFO' END,
        FP.ASSET_ID || ': Failure probability ' || ROUND(FP.FAILURE_PROB * 100, 1) || '% in next 24h',
        OBJECT_CONSTRUCT('failure_prob', FP.FAILURE_PROB, 'top_features', FP.TOP_FEATURES)
    FROM MFG_PDM_DB.ML.FAILURE_PREDICTIONS FP
    WHERE FP.FAILURE_PROB >= 0.60
    AND NOT EXISTS (SELECT 1 FROM MFG_PDM_DB.OPS.ALERT_HISTORY A WHERE A.ASSET_ID = FP.ASSET_ID AND A.ALERT_TYPE = 'FAILURE_PREDICTION' AND A.ALERT_TS >= DATEADD('hour', -1, CURRENT_TIMESTAMP()));

    -- RUL low alerts (<48h)
    INSERT INTO MFG_PDM_DB.OPS.ALERT_HISTORY (ASSET_ID, ALERT_TYPE, SEVERITY, MESSAGE, DETAIL)
    SELECT R.ASSET_ID, 'RUL_LOW',
        CASE WHEN R.ESTIMATED_RUL_HOURS <= 12 THEN 'CRITICAL' WHEN R.ESTIMATED_RUL_HOURS <= 48 THEN 'WARNING' ELSE 'INFO' END,
        R.ASSET_ID || ': Estimated RUL = ' || ROUND(R.ESTIMATED_RUL_HOURS, 0) || ' hours',
        OBJECT_CONSTRUCT('rul_hours', R.ESTIMATED_RUL_HOURS, 'current_vib', R.CURRENT_VIBRATION)
    FROM MFG_PDM_DB.ML.RUL_ESTIMATES R
    WHERE R.ESTIMATED_RUL_HOURS <= 48 AND R.ESTIMATED_RUL_HOURS < 9999
    AND NOT EXISTS (SELECT 1 FROM MFG_PDM_DB.OPS.ALERT_HISTORY A WHERE A.ASSET_ID = R.ASSET_ID AND A.ALERT_TYPE = 'RUL_LOW' AND A.ALERT_TS >= DATEADD('hour', -1, CURRENT_TIMESTAMP()));

    -- Anomaly alerts
    INSERT INTO MFG_PDM_DB.OPS.ALERT_HISTORY (ASSET_ID, ALERT_TYPE, SEVERITY, MESSAGE, DETAIL)
    SELECT AN.ASSET_ID, 'ANOMALY',
        CASE WHEN AN.PERCENTILE >= 0.95 THEN 'WARNING' ELSE 'INFO' END,
        AN.ASSET_ID || ': Anomaly detected - vibration ' || ROUND(AN.VALUE, 2) || ' vs expected ' || ROUND(AN.FORECAST, 2),
        OBJECT_CONSTRUCT('value', AN.VALUE, 'forecast', AN.FORECAST, 'distance', AN.DISTANCE)
    FROM MFG_PDM_DB.ML.ANOMALY_SCORES AN
    WHERE AN.IS_ANOMALY = TRUE
    AND NOT EXISTS (SELECT 1 FROM MFG_PDM_DB.OPS.ALERT_HISTORY A WHERE A.ASSET_ID = AN.ASSET_ID AND A.ALERT_TYPE = 'ANOMALY' AND A.ALERT_TS >= DATEADD('hour', -1, CURRENT_TIMESTAMP()));

    RETURN 'Alert triage complete';
END;
$$;


-- ─── 6. SP_GENERATE_WO_DRAFTS ───────────────────────────────────────────────
-- Called by: TASK_TRIAGE_PIPELINE (every 15 minutes, after SP_TRIAGE_ALERTS)
CREATE OR REPLACE PROCEDURE MFG_PDM_DB.OPS.SP_GENERATE_WO_DRAFTS()
RETURNS VARCHAR
LANGUAGE SQL
COMMENT = 'Auto-generates work order drafts from critical assets and high failure predictions.'
EXECUTE AS CALLER
AS
$$
BEGIN
    -- WO from rule engine (CRITICAL/WARNING)
    INSERT INTO MFG_PDM_DB.OPS.WORK_ORDER_DRAFTS (ASSET_ID, PRIORITY, WO_TYPE, TITLE, DESCRIPTION, RECOMMENDED_ACTION, SOURCE, TRIGGER_DETAIL)
    SELECT H.ASSET_ID,
        CASE H.RULE_STATUS WHEN 'CRITICAL' THEN 'P1-EMERGENCY' WHEN 'WARNING' THEN 'P2-URGENT' ELSE 'P3-PLANNED' END,
        'PdM',
        H.ASSET_TYPE || ' ' || H.ASSET_ID || ' - ' || H.RULE_STATUS || ' Health Alert',
        'Asset ' || H.ASSET_ID || ' in ' || H.RULE_STATUS || ' status. Health score: ' || COALESCE(H.HEALTH_SCORE::VARCHAR, 'N/A') || '/100. '
            || 'Vibration: ' || ROUND(COALESCE(H.AVG_VIBRATION,0),2) || ' mm/s (' || ROUND(COALESCE(H.VIB_PCT_OF_LIMIT,0)*100,1) || '% of limit).',
        CASE WHEN H.VIB_PCT_OF_LIMIT >= 0.90 THEN 'Inspect bearings and rotating components.'
             WHEN H.TEMP_PCT_OF_LIMIT >= 0.90 THEN 'Check cooling system and lubrication.'
             ELSE 'Perform comprehensive inspection.' END,
        'RULE_ENGINE',
        OBJECT_CONSTRUCT('rule_status', H.RULE_STATUS, 'health_score', H.HEALTH_SCORE)
    FROM MFG_PDM_DB.CURATED.DT_ASSET_HEALTH H
    WHERE H.RULE_STATUS IN ('CRITICAL', 'WARNING')
    AND NOT EXISTS (SELECT 1 FROM MFG_PDM_DB.OPS.WORK_ORDER_DRAFTS W WHERE W.ASSET_ID = H.ASSET_ID AND W.STATUS = 'DRAFT' AND W.CREATED_AT >= DATEADD('hour', -4, CURRENT_TIMESTAMP()));

    -- WO from ML predictions (>60%)
    INSERT INTO MFG_PDM_DB.OPS.WORK_ORDER_DRAFTS (ASSET_ID, PRIORITY, WO_TYPE, TITLE, DESCRIPTION, RECOMMENDED_ACTION, SOURCE, TRIGGER_DETAIL)
    SELECT FP.ASSET_ID,
        CASE WHEN FP.FAILURE_PROB >= 0.80 THEN 'P1-EMERGENCY' ELSE 'P2-URGENT' END,
        'PdM',
        'ML Prediction: ' || FP.ASSET_ID || ' - ' || ROUND(FP.FAILURE_PROB * 100, 0) || '% failure probability',
        'ML model predicts ' || ROUND(FP.FAILURE_PROB * 100, 1) || '% probability of failure within 24 hours.',
        'Schedule predictive maintenance within ' || CASE WHEN FP.FAILURE_PROB >= 0.80 THEN '4' ELSE '12' END || ' hours.',
        'ML_PREDICTION', FP.TOP_FEATURES
    FROM MFG_PDM_DB.ML.FAILURE_PREDICTIONS FP
    WHERE FP.FAILURE_PROB >= 0.60
    AND NOT EXISTS (SELECT 1 FROM MFG_PDM_DB.OPS.WORK_ORDER_DRAFTS W WHERE W.ASSET_ID = FP.ASSET_ID AND W.SOURCE = 'ML_PREDICTION' AND W.STATUS = 'DRAFT' AND W.CREATED_AT >= DATEADD('hour', -4, CURRENT_TIMESTAMP()));

    RETURN 'Work order draft generation complete';
END;
$$;
