-- =============================================================================
-- 02_TABLES: OPS Schema — Alert history, work order drafts, config
-- =============================================================================

CREATE OR REPLACE TABLE MFG_PDM_DB.OPS.ALERT_HISTORY (
    ALERT_ID        VARCHAR NOT NULL DEFAULT UUID_STRING(),
    ASSET_ID        VARCHAR NOT NULL,
    ALERT_TS        TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ALERT_TYPE      VARCHAR COMMENT 'THRESHOLD_BREACH, ANOMALY, FAILURE_PREDICTION, RUL_LOW',
    SEVERITY        VARCHAR COMMENT 'CRITICAL, WARNING, INFO',
    MESSAGE         VARCHAR,
    DETAIL          VARIANT,
    ACKNOWLEDGED    BOOLEAN DEFAULT FALSE,
    ACKNOWLEDGED_BY VARCHAR,
    ACKNOWLEDGED_AT TIMESTAMP_NTZ,
    CONSTRAINT PK_ALERTS PRIMARY KEY (ALERT_ID)
) COMMENT = 'Alert history from all monitoring sources';

CREATE OR REPLACE TABLE MFG_PDM_DB.OPS.WORK_ORDER_DRAFTS (
    DRAFT_ID           VARCHAR NOT NULL DEFAULT UUID_STRING(),
    ASSET_ID           VARCHAR NOT NULL,
    CREATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIORITY           VARCHAR COMMENT 'P1-EMERGENCY, P2-URGENT, P3-PLANNED, P4-ROUTINE',
    WO_TYPE            VARCHAR COMMENT 'CM=corrective, PM=preventive, PdM=predictive',
    TITLE              VARCHAR,
    DESCRIPTION        VARCHAR,
    RECOMMENDED_ACTION VARCHAR,
    SOURCE             VARCHAR COMMENT 'RULE_ENGINE, ML_PREDICTION, ANOMALY_DETECTION',
    TRIGGER_DETAIL     VARIANT,
    STATUS             VARCHAR DEFAULT 'DRAFT' COMMENT 'DRAFT, APPROVED, DISPATCHED, CANCELLED',
    APPROVED_BY        VARCHAR,
    APPROVED_AT        TIMESTAMP_NTZ,
    CONSTRAINT PK_WO_DRAFTS PRIMARY KEY (DRAFT_ID)
) COMMENT = 'Auto-generated work order drafts from predictive maintenance';

CREATE OR REPLACE TABLE MFG_PDM_DB.OPS.CONFIG (
    KEY        VARCHAR NOT NULL,
    VALUE      VARCHAR NOT NULL,
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Operational config: alert thresholds, model settings';
