-- =============================================================================
-- 03_SEED_DATA: Maintenance documentation (40 entries for Cortex Search)
-- =============================================================================

TRUNCATE TABLE IF EXISTS MFG_PDM_DB.RAW.MAINT_DOCS;
INSERT INTO MFG_PDM_DB.RAW.MAINT_DOCS VALUES
('DOC-001','CNC','Spindle Bearing Failure','SYMPTOMS','High vibration readings above 5 mm/s. Grinding or squealing noise during high-speed operation. Increased spindle temperature by 10-15C above normal. Reduced surface finish quality on machined parts.'),
('DOC-002','CNC','Spindle Bearing Failure','CAUSES','Normal wear after 8000-12000 operating hours. Contamination from coolant ingress. Excessive radial or axial loads from improper cutting parameters. Insufficient or degraded lubrication.'),
('DOC-003','CNC','Spindle Bearing Failure','INSPECTION','Check vibration spectrum for bearing defect frequencies (BPFO, BPFI, BSF). Measure temperature differential between bearing housing and ambient. Inspect grease condition for discoloration or metal particles. Run spindle warm-up cycle and monitor acceleration envelope.'),
('DOC-004','CNC','Spindle Bearing Failure','FIX','Replace bearing set (SP-001). Clean bearing housing thoroughly. Apply correct preload per manufacturer spec. Verify spindle runout < 3 microns after replacement. Run 2-hour break-in cycle at graduated speeds.'),
('DOC-005','CNC','Spindle Bearing Failure','SAFETY','Lock out spindle drive before disassembly. Use proper lifting equipment for spindle cartridge (>50kg). Wear cut-resistant gloves when handling bearings. Ensure coolant system is depressurized.'),
('DOC-006','CNC','Coolant System Overheating','SYMPTOMS','Coolant temperature exceeding 35C. Thermal growth causing dimensional drift. Tool life reduction of 30-50%. Machine thermal error compensation activating frequently.'),
('DOC-007','CNC','Coolant System Overheating','CAUSES','Clogged coolant filters restricting flow. Failed coolant pump (SP-002). Heat exchanger fouling from hard water deposits. Insufficient coolant concentration below 5%.'),
('DOC-008','CNC','Coolant System Overheating','FIX','Replace coolant filters. If pump failure, replace assembly (SP-002). Clean heat exchanger with descaling solution. Adjust coolant concentration to 6-8%. Verify flow rate meets spec of 20 L/min minimum.'),
('DOC-009','Robot','Servo Motor Degradation','SYMPTOMS','Increased following error during motion. Servo alarm codes 1300-1399. Audible clicking or grinding from axis drive. Position accuracy degradation >0.1mm.'),
('DOC-010','Robot','Servo Motor Degradation','CAUSES','Bearing wear in servo motor after 20000+ hours. Encoder contamination or misalignment. Excessive payload causing continuous high-torque operation. Ambient temperature consistently above 40C.'),
('DOC-011','Robot','Servo Motor Degradation','INSPECTION','Check servo motor current draw during standard test motion. Compare encoder feedback with actual position using laser tracker. Measure motor housing temperature during peak load. Review torque utilization logs for sustained >80% usage.'),
('DOC-012','Robot','Servo Motor Degradation','FIX','Replace servo motor (SP-004). Recalibrate axis after motor replacement. Update robot controller parameters for new motor. Run acceptance test program verifying path accuracy.'),
('DOC-013','Robot','Harmonic Drive Wear','SYMPTOMS','Increased backlash in affected axis >0.05mm. Vibration increase during direction changes. Audible gear meshing noise. Reduced repeat accuracy.'),
('DOC-014','Robot','Harmonic Drive Wear','FIX','Replace harmonic drive unit (SP-005). Requires axis disassembly and bearing replacement. Recalibrate mastering after replacement. Expected downtime: 8-12 hours.'),
('DOC-015','Robot','Wrist Seal Leak','SYMPTOMS','Oil residue visible around wrist joint. Reduced wrist payload capacity. Servo errors on axes 5 and 6. Contamination of work area.'),
('DOC-016','Robot','Wrist Seal Leak','FIX','Replace wrist seal kit (SP-006). Clean and inspect gear train for contamination. Refill with approved grease specification. Verify no air ingress in sealed chamber.'),
('DOC-017','Conveyor','Belt Tracking Issues','SYMPTOMS','Belt drifting to one side. Uneven belt edge wear. Material spillage at transfer points. Increased motor current draw.'),
('DOC-018','Conveyor','Belt Tracking Issues','CAUSES','Misaligned idler rollers. Uneven material loading. Belt splice failure. Frame distortion from thermal expansion.'),
('DOC-019','Conveyor','Belt Tracking Issues','FIX','Realign idler rollers using laser alignment tool. Replace belt set if worn (SP-007). Adjust take-up tension to manufacturer spec. Install training idlers at regular intervals.'),
('DOC-020','Pump','Mechanical Seal Failure','SYMPTOMS','Visible fluid leakage at seal face. Increased vibration at seal frequencies. Drop in discharge pressure. Cavitation noise during operation.'),
('DOC-021','Pump','Mechanical Seal Failure','CAUSES','Dry running from air entrainment. Seal face contamination from particles >10 microns. Misalignment between pump and motor >0.05mm. Thermal shock from rapid temperature changes.'),
('DOC-022','Pump','Mechanical Seal Failure','FIX','Replace mechanical seal assembly (SP-009). Check and correct shaft alignment. Verify seal flush system flow and pressure. Run pump through startup procedure with seal monitoring.'),
('DOC-023','Pump','Impeller Imbalance','SYMPTOMS','High vibration at 1x RPM frequency. Increased bearing temperature. Pressure pulsations in discharge line. Cavitation at normal operating conditions.'),
('DOC-024','Pump','Impeller Imbalance','FIX','Replace impeller (SP-010). Dynamically balance to G2.5 standard. Check wear ring clearances. Verify pump curve after reassembly.'),
('DOC-025','Compressor','Air End Overheating','SYMPTOMS','Discharge temperature exceeding 100C. Thermal cutout activation. Oil degradation and varnishing. Reduced air output capacity.'),
('DOC-026','Compressor','Air End Overheating','CAUSES','Clogged air filter element (SP-011). Failed thermostatic valve. Oil cooler fouling. Insufficient ventilation in compressor room (ambient >40C).'),
('DOC-027','Compressor','Air End Overheating','FIX','Replace air filter element (SP-011). Clean oil cooler with compressed air. Check and replace thermostatic valve if stuck. Verify room ventilation provides <40C ambient. Change oil if discolored or above TAN 2.0.'),
('DOC-028','Compressor','Oil Separator Failure','SYMPTOMS','High oil carryover (>5 ppm in discharged air). Oil level dropping faster than normal. Oil mist visible at point-of-use. Increased energy consumption.'),
('DOC-029','Compressor','Oil Separator Failure','FIX','Replace oil separator element (SP-012). Check minimum pressure valve operation. Verify oil return line is not blocked. Monitor oil consumption for 48 hours after replacement.'),
('DOC-030','Press','Hydraulic Seal Degradation','SYMPTOMS','Slow press speed or reduced tonnage. Oil leakage around cylinder. Pressure drop during dwell phase. Increased pump cycling frequency.'),
('DOC-031','Press','Hydraulic Seal Degradation','CAUSES','Normal wear after 2-5 million cycles. Contaminated hydraulic oil (NAS >9). Operating temperature exceeding 60C. Side loading from die misalignment.'),
('DOC-032','Press','Hydraulic Seal Degradation','FIX','Replace hydraulic seal kit (SP-014). Flush hydraulic system and replace oil. Install new filters. Check cylinder bore for scoring. Verify press tonnage after reassembly.'),
('DOC-033','Press','Clutch/Brake Wear','SYMPTOMS','Increased stopping time >50ms above spec. Brake temperature exceeding 80C. Clutch slip during engagement. Uneven stroke speed.'),
('DOC-034','Press','Clutch/Brake Wear','FIX','Replace clutch/brake assembly (SP-015). Adjust air gap to manufacturer spec. Verify stopping time meets OSHA requirements. Run 100 test cycles before production.'),
('DOC-035','CNC','Lubrication System Failure','SYMPTOMS','Way lube alarm on controller. Increased axis friction causing servo errors. Visible metal-to-metal contact marks on guideways. Increased power consumption during rapid traverse.'),
('DOC-036','CNC','Lubrication System Failure','CAUSES','Clogged lubrication distribution lines. Failed metering pump. Incorrect lubricant viscosity. Air in lubrication system.'),
('DOC-037','CNC','Lubrication System Failure','FIX','Flush and clean distribution lines. Replace metering pump if faulty. Refill with correct ISO VG-68 way lube. Bleed air from system. Verify flow to all lubrication points.'),
('DOC-038','Conveyor','Gearbox Failure','SYMPTOMS','Abnormal noise from gearbox. Oil leakage at seals. Increased operating temperature. Vibration at gear mesh frequencies.'),
('DOC-039','Conveyor','Gearbox Failure','CAUSES','Insufficient oil level or degraded oil (SP-020). Bearing failure from contamination. Gear tooth wear from overloading. Misalignment between motor and gearbox.'),
('DOC-040','Conveyor','Gearbox Failure','FIX','Change gearbox oil (SP-020). Replace bearings if damaged. Check gear tooth contact pattern. Realign motor coupling. Monitor temperature for 48 hours after repair.');
