-- =============================================================================
-- 03_SEED_DATA: Synthetic transactional data
-- =============================================================================
-- Generates production orders, downtime events, failure events, work orders
-- Run AFTER 01_reference_data.sql
-- =============================================================================

-- ===== PRODUCTION ORDERS (~2160 rows: 90 days x 8 lines x 3 shifts) =====
TRUNCATE TABLE IF EXISTS MFG_PDM_DB.RAW.PRODUCTION_ORDERS;
INSERT INTO MFG_PDM_DB.RAW.PRODUCTION_ORDERS
SELECT
    'PO-' || LPAD(ROW_NUMBER() OVER (ORDER BY D.DT, PL.LINE_ID, S.SHIFT), 6, '0'),
    PL.LINE_ID,
    'SKU-' || LPAD(UNIFORM(1, 20, RANDOM()), 3, '0'),
    D.DT, S.SHIFT,
    480,
    480 - UNIFORM(10, 60, RANDOM()),
    ROUND(UNIFORM(8, 25, RANDOM()) + UNIFORM(0, 99, RANDOM()) / 100.0, 2),
    UNIFORM(800, 2000, RANDOM()) AS TC,
    0, 0
FROM MFG_PDM_DB.RAW.PRODUCTION_LINES PL,
     (SELECT DATEADD('day', -SEQ4(), CURRENT_DATE()) AS DT FROM TABLE(GENERATOR(ROWCOUNT => 90))) D,
     (SELECT column1 AS SHIFT FROM VALUES ('A'), ('B'), ('C')) S;

-- Set scrap/good counts
UPDATE MFG_PDM_DB.RAW.PRODUCTION_ORDERS
SET SCRAP_COUNT = FLOOR(TOTAL_COUNT * (UNIFORM(1, 50, RANDOM()) / 1000.0)),
    GOOD_COUNT = TOTAL_COUNT - SCRAP_COUNT;

-- ===== DOWNTIME EVENTS (~250) =====
TRUNCATE TABLE IF EXISTS MFG_PDM_DB.RAW.DOWNTIME_EVENTS;
INSERT INTO MFG_PDM_DB.RAW.DOWNTIME_EVENTS
SELECT
  'DT-' || LPAD(ROW_NUMBER() OVER (ORDER BY RANDOM()), 5, '0'),
  A.ASSET_ID, A.LINE_ID,
  DATEADD('minute', UNIFORM(0, 129600, RANDOM()), DATEADD('day', -90, CURRENT_TIMESTAMP())) AS ST,
  DATEADD('minute', UNIFORM(30, 480, RANDOM()), ST),
  CASE UNIFORM(1,6,RANDOM()) WHEN 1 THEN 'EQUIPMENT_FAILURE' WHEN 2 THEN 'PM_SCHEDULED'
    WHEN 3 THEN 'CHANGEOVER' WHEN 4 THEN 'MATERIAL_SHORTAGE' WHEN 5 THEN 'OPERATOR' ELSE 'QUALITY_HOLD'
  END AS RC,
  CASE WHEN RC IN ('PM_SCHEDULED','CHANGEOVER') THEN TRUE ELSE FALSE END
FROM MFG_PDM_DB.RAW.ASSETS A, TABLE(GENERATOR(ROWCOUNT => 4)) G
WHERE UNIFORM(0,1,RANDOM()) > 0.05;

-- ===== FAILURE EVENTS (~80-100) =====
TRUNCATE TABLE IF EXISTS MFG_PDM_DB.RAW.FAILURE_EVENTS;
INSERT INTO MFG_PDM_DB.RAW.FAILURE_EVENTS (ASSET_ID, FAILURE_TS, FAILURE_MODE, DEGRADATION_START_TS, DEGRADATION_HOURS, DOWNTIME_HOURS)
SELECT
  A.ASSET_ID,
  DATEADD('hour', UNIFORM(24, 2100, RANDOM()), DATEADD('day', -90, CURRENT_TIMESTAMP())) AS FT,
  CASE UNIFORM(1,5,RANDOM()) WHEN 1 THEN 'BEARING_WEAR' WHEN 2 THEN 'OVERHEATING'
    WHEN 3 THEN 'IMBALANCE' WHEN 4 THEN 'SEAL_LEAK' ELSE 'LUBRICATION_FAILURE'
  END,
  DATEADD('hour', -UNIFORM(24, 72, RANDOM()), FT) AS DS,
  DATEDIFF('hour', DS, FT)::NUMBER(5,1),
  UNIFORM(2, 24, RANDOM())::NUMBER(5,1)
FROM MFG_PDM_DB.RAW.ASSETS A, TABLE(GENERATOR(ROWCOUNT => 3)) G
WHERE UNIFORM(0,1,RANDOM()) > 0.4;

-- ===== WORK ORDERS (~300) =====
TRUNCATE TABLE IF EXISTS MFG_PDM_DB.RAW.WORK_ORDERS_HIST;
INSERT INTO MFG_PDM_DB.RAW.WORK_ORDERS_HIST
SELECT
  'WO-' || LPAD(ROW_NUMBER() OVER (ORDER BY RANDOM()), 5, '0'),
  A.ASSET_ID,
  DATEADD('hour', UNIFORM(24, 2100, RANDOM()), DATEADD('day', -90, CURRENT_TIMESTAMP())) AS CT,
  CASE WHEN UNIFORM(0,1,RANDOM()) > 0.1 THEN DATEADD('hour', UNIFORM(2, 48, RANDOM()), CT) ELSE NULL END,
  CASE UNIFORM(1,3,RANDOM()) WHEN 1 THEN 'CM' WHEN 2 THEN 'PM' ELSE 'PdM' END AS WT,
  CASE UNIFORM(1,4,RANDOM()) WHEN 1 THEN 'P1' WHEN 2 THEN 'P2' WHEN 3 THEN 'P3' ELSE 'P4' END,
  CASE WHEN WT='CM' THEN CASE UNIFORM(1,5,RANDOM()) WHEN 1 THEN 'BEARING_WEAR' WHEN 2 THEN 'OVERHEATING' WHEN 3 THEN 'IMBALANCE' WHEN 4 THEN 'SEAL_LEAK' ELSE 'LUBRICATION_FAILURE' END ELSE NULL END,
  CASE WHEN WT='CM' THEN 'Component degradation identified' ELSE NULL END,
  CASE WT WHEN 'CM' THEN 'Corrective repair completed' WHEN 'PM' THEN 'Scheduled maintenance done' ELSE 'Predictive replacement' END,
  NULL, 'Tech-' || LPAD(UNIFORM(1,15,RANDOM()),2,'0'), UNIFORM(30,480,RANDOM()),
  UNIFORM(100,5000,RANDOM())::NUMBER(10,2), 'Maintenance completed per procedure.'
FROM MFG_PDM_DB.RAW.ASSETS A, TABLE(GENERATOR(ROWCOUNT => 5)) G;
