-- =============================================================================
-- DYNAMIC TABLES (CURATED Schema)
-- Auto-refreshing materialized views that power the dashboard
-- Snowflake handles all orchestration — no ETL code needed
-- =============================================================================

-- DT_SENSOR_CLEAN: First stage — dedup + cleanse raw sensor data
-- Removes impossible values, forward-fills nulls, flags idle machines
CREATE OR REPLACE DYNAMIC TABLE MFG_PDM_DB.CURATED.DT_SENSOR_CLEAN
  TARGET_LAG = 'DOWNSTREAM'
  WAREHOUSE = MFG_PDM_WH
  COMMENT = 'Cleaned sensor readings: deduped, impossible values removed, nulls forward-filled, rpm=0 flagged'
AS
WITH DEDUPED AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY ASSET_ID, READING_TS ORDER BY INGEST_TS DESC) AS RN
    FROM MFG_PDM_DB.RAW.SENSOR_READINGS
),
CLEANED AS (
    SELECT D.ASSET_ID, D.READING_TS,
        CASE WHEN D.VIBRATION_MM_S < 0 OR D.VIBRATION_MM_S > 50 THEN NULL ELSE D.VIBRATION_MM_S END AS VIBRATION_MM_S_RAW,
        CASE WHEN D.TEMPERATURE_C < -10 OR D.TEMPERATURE_C > 200 THEN NULL ELSE D.TEMPERATURE_C END AS TEMPERATURE_C_RAW,
        CASE WHEN D.RPM < 0 THEN 0 ELSE D.RPM END AS RPM,
        CASE WHEN D.PRESSURE_BAR < 0 OR D.PRESSURE_BAR > 500 THEN NULL ELSE D.PRESSURE_BAR END AS PRESSURE_BAR,
        CASE WHEN D.POWER_KW < 0 THEN 0 ELSE D.POWER_KW END AS POWER_KW,
        D.SOURCE, A.ASSET_TYPE, A.LINE_ID, A.MAX_VIBRATION_MM_S, A.MAX_TEMP_C, A.RATED_RPM
    FROM DEDUPED D
    JOIN MFG_PDM_DB.RAW.ASSETS A ON D.ASSET_ID = A.ASSET_ID
    WHERE D.RN = 1
)
SELECT ASSET_ID, READING_TS,
    COALESCE(VIBRATION_MM_S_RAW, LAG(VIBRATION_MM_S_RAW) IGNORE NULLS OVER (PARTITION BY ASSET_ID ORDER BY READING_TS)) AS VIBRATION_MM_S,
    COALESCE(TEMPERATURE_C_RAW, LAG(TEMPERATURE_C_RAW) IGNORE NULLS OVER (PARTITION BY ASSET_ID ORDER BY READING_TS)) AS TEMPERATURE_C,
    RPM, PRESSURE_BAR, POWER_KW, SOURCE, ASSET_TYPE, LINE_ID,
    MAX_VIBRATION_MM_S, MAX_TEMP_C, RATED_RPM,
    CASE WHEN RPM = 0 AND POWER_KW < 1 THEN TRUE ELSE FALSE END AS IS_NOT_RUNNING
FROM CLEANED;


-- DT_SENSOR_FEATURES_15M: 15-minute aggregated features with threshold proximity
CREATE OR REPLACE DYNAMIC TABLE MFG_PDM_DB.CURATED.DT_SENSOR_FEATURES_15M
  TARGET_LAG = 'DOWNSTREAM'
  WAREHOUSE = MFG_PDM_WH
  COMMENT = '15-minute aggregated sensor features per asset with threshold proximity and rolling stats'
AS
WITH WINDOWED AS (
    SELECT ASSET_ID, ASSET_TYPE, LINE_ID, MAX_VIBRATION_MM_S, MAX_TEMP_C, RATED_RPM,
        TIME_SLICE(READING_TS, 15, 'MINUTE', 'START') AS WINDOW_START,
        AVG(VIBRATION_MM_S) AS AVG_VIB, MIN(VIBRATION_MM_S) AS MIN_VIB,
        MAX(VIBRATION_MM_S) AS MAX_VIB, STDDEV(VIBRATION_MM_S) AS STD_VIB,
        AVG(TEMPERATURE_C) AS AVG_TEMP, MIN(TEMPERATURE_C) AS MIN_TEMP,
        MAX(TEMPERATURE_C) AS MAX_TEMP, STDDEV(TEMPERATURE_C) AS STD_TEMP,
        AVG(RPM) AS AVG_RPM, STDDEV(RPM) AS STD_RPM,
        AVG(PRESSURE_BAR) AS AVG_PRES, AVG(POWER_KW) AS AVG_PWR, MAX(POWER_KW) AS MAX_PWR,
        COUNT(*) AS READING_CNT,
        SUM(CASE WHEN IS_NOT_RUNNING THEN 1 ELSE 0 END) AS NOT_RUNNING_CNT
    FROM MFG_PDM_DB.CURATED.DT_SENSOR_CLEAN
    GROUP BY ASSET_ID, ASSET_TYPE, LINE_ID, MAX_VIBRATION_MM_S, MAX_TEMP_C, RATED_RPM,
        TIME_SLICE(READING_TS, 15, 'MINUTE', 'START')
)
SELECT ASSET_ID, ASSET_TYPE, LINE_ID, WINDOW_START,
    ROUND(AVG_VIB, 3) AS AVG_VIBRATION, ROUND(MIN_VIB, 3) AS MIN_VIBRATION,
    ROUND(MAX_VIB, 3) AS MAX_VIBRATION, ROUND(STD_VIB, 4) AS STD_VIBRATION,
    ROUND(AVG_TEMP, 2) AS AVG_TEMPERATURE, ROUND(MIN_TEMP, 2) AS MIN_TEMPERATURE,
    ROUND(MAX_TEMP, 2) AS MAX_TEMPERATURE, ROUND(STD_TEMP, 3) AS STD_TEMPERATURE,
    ROUND(AVG_RPM, 1) AS AVG_RPM, ROUND(STD_RPM, 2) AS STD_RPM,
    ROUND(AVG_PRES, 2) AS AVG_PRESSURE, ROUND(AVG_PWR, 2) AS AVG_POWER, ROUND(MAX_PWR, 2) AS MAX_POWER,
    ROUND(AVG_VIB / NULLIF(MAX_VIBRATION_MM_S, 0), 3) AS VIB_PCT_OF_LIMIT,
    ROUND(AVG_TEMP / NULLIF(MAX_TEMP_C, 0), 3) AS TEMP_PCT_OF_LIMIT,
    ROUND(AVG_VIB - LAG(AVG_VIB) OVER (PARTITION BY ASSET_ID ORDER BY WINDOW_START), 3) AS VIB_DELTA,
    ROUND(AVG_TEMP - LAG(AVG_TEMP) OVER (PARTITION BY ASSET_ID ORDER BY WINDOW_START), 3) AS TEMP_DELTA,
    READING_CNT, NOT_RUNNING_CNT > 0 AS IS_RUNNING,
    MAX_VIBRATION_MM_S, MAX_TEMP_C, RATED_RPM
FROM WINDOWED;


-- DT_ASSET_HEALTH: Per-asset health combining rules + ML
CREATE OR REPLACE DYNAMIC TABLE MFG_PDM_DB.CURATED.DT_ASSET_HEALTH
  TARGET_LAG = '2 minutes'
  WAREHOUSE = MFG_PDM_WH
  COMMENT = 'Current health status per asset combining rule-based thresholds + ML anomaly/failure/RUL scores'
AS
WITH LATEST AS (
    SELECT *, ROW_NUMBER() OVER (PARTITION BY ASSET_ID ORDER BY WINDOW_START DESC) AS RN
    FROM MFG_PDM_DB.CURATED.DT_SENSOR_FEATURES_15M
    WHERE IS_RUNNING = FALSE
)
SELECT
    L.ASSET_ID, L.ASSET_TYPE, L.LINE_ID, PL.PLANT_ID, A.CRITICALITY,
    A.MANUFACTURER, A.MODEL, A.INSTALL_DATE, A.HOURLY_DOWNTIME_COST_USD,
    L.WINDOW_START AS LAST_READING_TS,
    L.AVG_VIBRATION, L.AVG_TEMPERATURE, L.AVG_RPM, L.AVG_PRESSURE, L.AVG_POWER,
    L.VIB_PCT_OF_LIMIT, L.TEMP_PCT_OF_LIMIT, L.VIB_DELTA, L.TEMP_DELTA, L.STD_VIBRATION,
    CASE
        WHEN L.VIB_PCT_OF_LIMIT >= 0.90 OR L.TEMP_PCT_OF_LIMIT >= 0.90 THEN 'CRITICAL'
        WHEN L.VIB_PCT_OF_LIMIT >= 0.75 OR L.TEMP_PCT_OF_LIMIT >= 0.75 THEN 'WARNING'
        WHEN L.VIB_PCT_OF_LIMIT >= 0.60 OR L.TEMP_PCT_OF_LIMIT >= 0.60 THEN 'WATCH'
        ELSE 'HEALTHY'
    END AS RULE_STATUS,
    ROUND(100 * (1 - GREATEST(COALESCE(L.VIB_PCT_OF_LIMIT,0), COALESCE(L.TEMP_PCT_OF_LIMIT,0))), 1) AS HEALTH_SCORE_RULE,
    FP.FAILURE_PROB AS ANOMALY_SCORE,
    FP.FAILURE_PROB,
    RUL.ESTIMATED_RUL_HOURS AS RUL_HOURS,
    ROUND(GREATEST(0, LEAST(100,
        100 * (1 - GREATEST(COALESCE(L.VIB_PCT_OF_LIMIT,0), COALESCE(L.TEMP_PCT_OF_LIMIT,0)))
        * (1 - COALESCE(FP.FAILURE_PROB, 0))
        * LEAST(1.0, COALESCE(RUL.ESTIMATED_RUL_HOURS, 9999) / 720)
    )), 1) AS HEALTH_SCORE
FROM LATEST L
JOIN MFG_PDM_DB.RAW.ASSETS A ON L.ASSET_ID = A.ASSET_ID
JOIN MFG_PDM_DB.RAW.PRODUCTION_LINES PL ON L.LINE_ID = PL.LINE_ID
LEFT JOIN MFG_PDM_DB.ML.FAILURE_PREDICTIONS FP ON L.ASSET_ID = FP.ASSET_ID
LEFT JOIN MFG_PDM_DB.ML.RUL_ESTIMATES RUL ON L.ASSET_ID = RUL.ASSET_ID
WHERE L.RN = 1;


-- DT_OEE_SHIFT: OEE per line per shift per day
CREATE OR REPLACE DYNAMIC TABLE MFG_PDM_DB.CURATED.DT_OEE_SHIFT
  TARGET_LAG = '5 minutes'
  WAREHOUSE = MFG_PDM_WH
  COMMENT = 'OEE metrics per production line per shift per day'
AS
SELECT
    PO.LINE_ID, PL.LINE_NAME, PL.PLANT_ID, P.PLANT_NAME,
    PO.SHIFT_DATE, PO.SHIFT, PO.PLANNED_RUNTIME_MIN, PO.RUN_TIME_MIN,
    PO.IDEAL_CYCLE_TIME_SEC, PO.TOTAL_COUNT, PO.GOOD_COUNT, PO.SCRAP_COUNT,
    ROUND(PO.RUN_TIME_MIN / NULLIF(PO.PLANNED_RUNTIME_MIN, 0), 4) AS AVAILABILITY,
    ROUND(LEAST((PO.IDEAL_CYCLE_TIME_SEC * PO.TOTAL_COUNT) / NULLIF(PO.RUN_TIME_MIN * 60, 0), 1.0), 4) AS PERFORMANCE,
    ROUND(PO.GOOD_COUNT / NULLIF(PO.TOTAL_COUNT::FLOAT, 0), 4) AS QUALITY,
    ROUND(
        (PO.RUN_TIME_MIN / NULLIF(PO.PLANNED_RUNTIME_MIN, 0)) *
        LEAST((PO.IDEAL_CYCLE_TIME_SEC * PO.TOTAL_COUNT) / NULLIF(PO.RUN_TIME_MIN * 60, 0), 1.0) *
        (PO.GOOD_COUNT / NULLIF(PO.TOTAL_COUNT::FLOAT, 0)), 4
    ) AS OEE
FROM MFG_PDM_DB.RAW.PRODUCTION_ORDERS PO
JOIN MFG_PDM_DB.RAW.PRODUCTION_LINES PL ON PO.LINE_ID = PL.LINE_ID
JOIN MFG_PDM_DB.RAW.PLANTS P ON PL.PLANT_ID = P.PLANT_ID;


-- DT_OEE_LINE_DAILY: Daily OEE rollup per line
CREATE OR REPLACE DYNAMIC TABLE MFG_PDM_DB.CURATED.DT_OEE_LINE_DAILY
  TARGET_LAG = '5 minutes'
  WAREHOUSE = MFG_PDM_WH
  COMMENT = 'Daily OEE rollup per production line'
AS
SELECT LINE_ID, LINE_NAME, PLANT_ID, PLANT_NAME, SHIFT_DATE,
    SUM(PLANNED_RUNTIME_MIN) AS PLANNED_RUNTIME_MIN, SUM(RUN_TIME_MIN) AS RUN_TIME_MIN,
    SUM(TOTAL_COUNT) AS TOTAL_COUNT, SUM(GOOD_COUNT) AS GOOD_COUNT, SUM(SCRAP_COUNT) AS SCRAP_COUNT,
    ROUND(SUM(RUN_TIME_MIN) / NULLIF(SUM(PLANNED_RUNTIME_MIN), 0), 4) AS AVAILABILITY,
    ROUND(AVG(PERFORMANCE), 4) AS PERFORMANCE,
    ROUND(SUM(GOOD_COUNT) / NULLIF(SUM(TOTAL_COUNT)::FLOAT, 0), 4) AS QUALITY,
    ROUND(AVG(OEE), 4) AS OEE
FROM MFG_PDM_DB.CURATED.DT_OEE_SHIFT
GROUP BY LINE_ID, LINE_NAME, PLANT_ID, PLANT_NAME, SHIFT_DATE;


-- DT_OEE_PLANT_DAILY: Daily OEE rollup per plant
CREATE OR REPLACE DYNAMIC TABLE MFG_PDM_DB.CURATED.DT_OEE_PLANT_DAILY
  TARGET_LAG = '5 minutes'
  WAREHOUSE = MFG_PDM_WH
  COMMENT = 'Daily OEE rollup per plant'
AS
SELECT PLANT_ID, PLANT_NAME, SHIFT_DATE,
    SUM(PLANNED_RUNTIME_MIN) AS PLANNED_RUNTIME_MIN, SUM(RUN_TIME_MIN) AS RUN_TIME_MIN,
    SUM(TOTAL_COUNT) AS TOTAL_COUNT, SUM(GOOD_COUNT) AS GOOD_COUNT, SUM(SCRAP_COUNT) AS SCRAP_COUNT,
    ROUND(AVG(AVAILABILITY), 4) AS AVAILABILITY, ROUND(AVG(PERFORMANCE), 4) AS PERFORMANCE,
    ROUND(AVG(QUALITY), 4) AS QUALITY, ROUND(AVG(OEE), 4) AS OEE
FROM MFG_PDM_DB.CURATED.DT_OEE_LINE_DAILY
GROUP BY PLANT_ID, PLANT_NAME, SHIFT_DATE;


-- DT_ASSET_360: 30-day comprehensive asset profile
CREATE OR REPLACE DYNAMIC TABLE MFG_PDM_DB.CURATED.DT_ASSET_360
  TARGET_LAG = '5 minutes'
  WAREHOUSE = MFG_PDM_WH
  COMMENT = 'One row per asset with 30-day MTBF, MTTR, failure count, downtime cost, last WO, spare-part status'
AS
WITH ASSET_FAILURES_30D AS (
    SELECT ASSET_ID, COUNT(*) AS FAILURE_COUNT_30D, SUM(DOWNTIME_HOURS) AS DOWNTIME_HOURS_30D
    FROM MFG_PDM_DB.RAW.FAILURE_EVENTS
    WHERE FAILURE_TS >= DATEADD('day', -30, CURRENT_TIMESTAMP())
    GROUP BY ASSET_ID
),
WO_STATS AS (
    SELECT ASSET_ID,
        COUNT(*) AS WO_COUNT_30D,
        COUNT(CASE WHEN WO_TYPE = 'CM' THEN 1 END) AS CM_COUNT_30D,
        SUM(DOWNTIME_MIN) AS TOTAL_DOWNTIME_MIN_30D,
        SUM(COST_USD) AS TOTAL_MAINT_COST_30D,
        AVG(CASE WHEN WO_TYPE = 'CM' THEN DOWNTIME_MIN END) AS AVG_REPAIR_MIN
    FROM MFG_PDM_DB.RAW.WORK_ORDERS_HIST
    WHERE CREATED_TS >= DATEADD('day', -30, CURRENT_TIMESTAMP())
    GROUP BY ASSET_ID
),
LAST_WO AS (
    SELECT ASSET_ID, WO_ID, WO_TYPE, CREATED_TS,
        ROW_NUMBER() OVER (PARTITION BY ASSET_ID ORDER BY CREATED_TS DESC) AS RN
    FROM MFG_PDM_DB.RAW.WORK_ORDERS_HIST
),
OPEN_PM AS (
    SELECT ASSET_ID, COUNT(*) AS OPEN_PM_COUNT
    FROM MFG_PDM_DB.RAW.WORK_ORDERS_HIST
    WHERE WO_TYPE = 'PM' AND CLOSED_TS IS NULL
    GROUP BY ASSET_ID
),
SPARE_STATUS AS (
    SELECT SP.ASSET_TYPE, COUNT(*) AS TOTAL_PARTS,
        SUM(CASE WHEN SP.ON_HAND_QTY <= SP.REORDER_POINT THEN 1 ELSE 0 END) AS PARTS_BELOW_REORDER
    FROM MFG_PDM_DB.RAW.SPARE_PARTS SP
    GROUP BY SP.ASSET_TYPE
)
SELECT
    A.ASSET_ID, A.ASSET_TYPE, A.LINE_ID, PL.PLANT_ID, A.CRITICALITY,
    A.MANUFACTURER, A.MODEL, A.INSTALL_DATE,
    DATEDIFF('day', A.INSTALL_DATE, CURRENT_DATE()) AS AGE_DAYS,
    A.HOURLY_DOWNTIME_COST_USD,
    COALESCE(AF.FAILURE_COUNT_30D, 0) AS FAILURE_COUNT_30D,
    COALESCE(AF.DOWNTIME_HOURS_30D, 0) AS DOWNTIME_HOURS_30D,
    ROUND(COALESCE(AF.DOWNTIME_HOURS_30D, 0) * A.HOURLY_DOWNTIME_COST_USD, 2) AS DOWNTIME_COST_30D,
    CASE WHEN COALESCE(AF.FAILURE_COUNT_30D, 0) > 0
        THEN ROUND((30 * 24 - COALESCE(AF.DOWNTIME_HOURS_30D, 0)) / AF.FAILURE_COUNT_30D, 1)
        ELSE 720 END AS MTBF_HOURS_30D,
    CASE WHEN COALESCE(WS.CM_COUNT_30D, 0) > 0
        THEN ROUND(WS.AVG_REPAIR_MIN / 60, 1) ELSE NULL END AS MTTR_HOURS_30D,
    COALESCE(WS.WO_COUNT_30D, 0) AS WO_COUNT_30D,
    COALESCE(WS.TOTAL_MAINT_COST_30D, 0) AS MAINT_COST_30D,
    LW.WO_ID AS LAST_WO_ID, LW.WO_TYPE AS LAST_WO_TYPE, LW.CREATED_TS AS LAST_WO_TS,
    COALESCE(OP.OPEN_PM_COUNT, 0) AS OPEN_PM_COUNT,
    SS.TOTAL_PARTS AS SPARE_PARTS_TOTAL,
    COALESCE(SS.PARTS_BELOW_REORDER, 0) AS SPARE_PARTS_LOW_STOCK
FROM MFG_PDM_DB.RAW.ASSETS A
JOIN MFG_PDM_DB.RAW.PRODUCTION_LINES PL ON A.LINE_ID = PL.LINE_ID
LEFT JOIN ASSET_FAILURES_30D AF ON A.ASSET_ID = AF.ASSET_ID
LEFT JOIN WO_STATS WS ON A.ASSET_ID = WS.ASSET_ID
LEFT JOIN LAST_WO LW ON A.ASSET_ID = LW.ASSET_ID AND LW.RN = 1
LEFT JOIN OPEN_PM OP ON A.ASSET_ID = OP.ASSET_ID
LEFT JOIN SPARE_STATUS SS ON A.ASSET_TYPE = SS.ASSET_TYPE;


-- DT_DOWNTIME_PARETO: Downtime by reason code, 30-day rolling
CREATE OR REPLACE DYNAMIC TABLE MFG_PDM_DB.CURATED.DT_DOWNTIME_PARETO
  TARGET_LAG = '5 minutes'
  WAREHOUSE = MFG_PDM_WH
  COMMENT = 'Downtime Pareto analysis: minutes and cost by reason code and line, 30-day rolling'
AS
SELECT
    DE.LINE_ID, PL.LINE_NAME, PL.PLANT_ID, DE.REASON_CODE, DE.IS_PLANNED,
    COUNT(*) AS EVENT_COUNT,
    ROUND(SUM(DATEDIFF('minute', DE.START_TS, DE.END_TS)), 0) AS DOWNTIME_MIN,
    ROUND(SUM(DATEDIFF('minute', DE.START_TS, DE.END_TS)) / 60.0, 1) AS DOWNTIME_HOURS
FROM MFG_PDM_DB.RAW.DOWNTIME_EVENTS DE
JOIN MFG_PDM_DB.RAW.PRODUCTION_LINES PL ON DE.LINE_ID = PL.LINE_ID
WHERE DE.START_TS >= DATEADD('day', -30, CURRENT_TIMESTAMP())
GROUP BY DE.LINE_ID, PL.LINE_NAME, PL.PLANT_ID, DE.REASON_CODE, DE.IS_PLANNED;
