-- =============================================================================
-- OPS SCHEMA TABLES
-- Operational layer: alerts, work order drafts, configuration
-- =============================================================================

CREATE OR REPLACE TABLE MFG_PDM_DB.OPS.ALERT_HISTORY (
    ALERT_ID VARCHAR(16777216) NOT NULL DEFAULT UUID_STRING(),
    ASSET_ID VARCHAR(16777216) NOT NULL,
    ALERT_TS TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    ALERT_TYPE VARCHAR(16777216) COMMENT 'THRESHOLD_BREACH, ANOMALY, FAILURE_PREDICTION, RUL_LOW',
    SEVERITY VARCHAR(16777216) COMMENT 'CRITICAL, WARNING, INFO',
    MESSAGE VARCHAR(16777216),
    DETAIL VARIANT,
    ACKNOWLEDGED BOOLEAN DEFAULT FALSE,
    ACKNOWLEDGED_BY VARCHAR(16777216),
    ACKNOWLEDGED_AT TIMESTAMP_NTZ(9),
    CONSTRAINT PK_ALERTS PRIMARY KEY (ALERT_ID)
) COMMENT = 'Alert history from all monitoring sources';

CREATE OR REPLACE TABLE MFG_PDM_DB.OPS.WORK_ORDER_DRAFTS (
    DRAFT_ID VARCHAR(16777216) NOT NULL DEFAULT UUID_STRING(),
    ASSET_ID VARCHAR(16777216) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIORITY VARCHAR(16777216) COMMENT 'P1-EMERGENCY, P2-URGENT, P3-PLANNED, P4-ROUTINE',
    WO_TYPE VARCHAR(16777216) COMMENT 'CM=corrective, PM=preventive, PdM=predictive',
    TITLE VARCHAR(16777216),
    DESCRIPTION VARCHAR(16777216),
    RECOMMENDED_ACTION VARCHAR(16777216),
    SOURCE VARCHAR(16777216) COMMENT 'RULE_ENGINE, ML_PREDICTION, ANOMALY_DETECTION',
    TRIGGER_DETAIL VARIANT COMMENT 'JSON with triggering metrics',
    STATUS VARCHAR(16777216) DEFAULT 'DRAFT' COMMENT 'DRAFT, APPROVED, DISPATCHED, CANCELLED',
    APPROVED_BY VARCHAR(16777216),
    APPROVED_AT TIMESTAMP_NTZ(9),
    CONSTRAINT PK_WO_DRAFTS PRIMARY KEY (DRAFT_ID)
) COMMENT = 'Auto-generated work order drafts from predictive maintenance scoring';

CREATE OR REPLACE TABLE MFG_PDM_DB.OPS.CONFIG (
    KEY VARCHAR(16777216) NOT NULL COMMENT 'Configuration parameter name',
    VALUE VARCHAR(16777216) NOT NULL COMMENT 'Configuration parameter value',
    UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP() COMMENT 'Last update timestamp'
) COMMENT = 'Operational configuration for alert thresholds, model settings, and integration modes';
